import { GridMetaDataType } from "@acuteinfo/common-base";
export const TRN002_TableMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Today's Transactions",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideHeader: false,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "30vh",
      max: "30vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "ACCT_NM",
      columnName: "AcctHolderName",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "ACCT_CD_NEW",
      columnName: "AcctCdNew",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "Chequeno",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "ENTERED_BRANCH_CD",
      columnName: "EnteredBranchCd",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "ENTERED_COMP_CD",
      columnName: "EnteredCompCd",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "PENDING_CYCLE",
      columnName: "PendingCycle",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "SCROLL1",
      columnName: "ScrollTokenNo",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "SDC",
      columnName: "SDC",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "TYPE_CD",
      columnName: "Trx",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "TRAN_CD",
      columnName: "Voucher No.",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "verifiedBy",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "Voucher No.",
      sequence: 1,
      componentType: "default",
      width: 100,
    },
    {
      accessor: "ACCT_CD_NEW",
      columnName: "AccountNo",
      sequence: 2,
      componentType: "default",
      width: 180,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AcctHolderName",
      sequence: 3,
      componentType: "default",
      width: 200,
    },
    {
      accessor: "TYPE_CD",
      columnName: "Trx",
      sequence: 4,
      componentType: "default",
      width: 20,
    },
    {
      accessor: "AMOUNT",
      columnName: "Amount",
      sequence: 5,
      componentType: "currency",
      width: 120,
      alignment: "right",
      isDisplayTotal: true,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 6,
      componentType: "default",
      width: 200,
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "Chequeno",
      sequence: 7,
      componentType: "default",
      width: 40,
    },
    {
      accessor: "SDC",
      columnName: "SDC",
      sequence: 8,
      componentType: "default",
      width: 80,
    },
    {
      accessor: "L_INST_DT",
      columnName: "ChequeDate",
      sequence: 9,
      componentType: "date",
      width: 110,
    },
    {
      accessor: "SCROLL1",
      columnName: "ScrollTokenNo",
      sequence: 10,
      componentType: "default",
      width: 100,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 11,
      componentType: "default",
      width: 80,
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "verifiedBy",
      sequence: 12,
      componentType: "default",
      width: 80,
    },
    {
      accessor: "PENDING_CYCLE",
      columnName: "PendingCycle",
      sequence: 13,
      componentType: "default",
      width: 110,
    },
    {
      accessor: "ENTERED_COMP_CD",
      columnName: "Bank",
      sequence: 14,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "ENTERED_BRANCH_CD",
      columnName: "EnteredBranch",
      sequence: 15,
      componentType: "default",
      width: 120,
    },
  ],
};
