import { GridMetaDataType } from "@acuteinfo/common-base";

export const confirmationGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 100,
      maxWidth: 100,
      minWidth: 100,
    },
    allowColumnReordering: true,
    hideFooter: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 35],
    defaultPageSize: 15,
    containerHeight: {
      min: "28vh",
      max: "28vh",
    },
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "VoucherNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "VoucherNo",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "LOCKER_NO",
      columnName: "lockerNumber",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "SIZE_NM",
      columnName: "lockerSize",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 110,
    },
    {
      accessor: "TYPE_CD",
      columnName: "Trx",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "RECEIPT_NO",
      columnName: "receiptNoL",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "RENT_PERIOD",
      columnName: "Period",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "AMOUNT",
      columnName: "rentAmt",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 200,
      showTooltip: true,
    },
    {
      accessor: "SERVICE_TAX_AMT",
      columnName: "GST",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 200,
      showTooltip: true,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
      showTooltip: true,
    },
    {
      accessor: "PENALTY_AMOUNT",
      columnName: "penaltyAmt",
      sequence: 9,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 200,
      showTooltip: true,
    },
    {
      accessor: "PENALTY_GST",
      columnName: "gstOnPenalty",
      sequence: 10,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 200,
      showTooltip: true,
    },
  ],
};
