import { GridMetaDataType } from "@acuteinfo/common-base";

export const confirmationTodayTrns: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 100,
      maxWidth: 100,
      minWidth: 100,
    },
    allowColumnReordering: true,
    hideFooter: false,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 35],
    defaultPageSize: 15,
    containerHeight: {
      min: "40vh",
      max: "40vh",
    },
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "VoucherNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "COMP_CD",
      columnName: "ACNo",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "ACCT_CD",
      columnName: "",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account_Name",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "TYPE_CD",
      columnName: "Trx",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 90,
      minWidth: 90,
      maxWidth: 100,
      showTooltip: true,
    },

    {
      accessor: "CR_AMOUNT",
      columnName: "CreditAmount",
      sequence: 7,
      alignment: "left",
      componentType: "currency",
      width: 150,
      minWidth: 100,
      maxWidth: 260,
      showTooltip: true,
    },
    {
      accessor: "DR_AMOUNT",
      columnName: "DebitAmount",
      sequence: 7,
      alignment: "left",
      componentType: "currency",
      width: 150,
      minWidth: 100,
      maxWidth: 260,
      showTooltip: true,
    },
  ],
};
