import { GridMetaDataType } from "@acuteinfo/common-base";

export const insuranceEntryConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "65vh",
      max: "65vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "id",
      columnName: "SrNo",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "AC_DTL_DISP",
      columnName: "AccountDetails",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 400,
      minWidth: 350,
      maxWidth: 450,
    },
    {
      accessor: "POLICY_NO",
      columnName: "PolicyNo",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "INSURANCE_DATE",
      columnName: "InsuranceDate",
      sequence: 3,
      alignment: "center",
      componentType: "date",
      width: 110,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "DUE_DATE",
      columnName: "DueDate",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      width: 90,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "INSURANCE_AMOUNT",
      columnName: "InsuranceAmount",
      sequence: 5,
      alignment: "right",
      componentType: "currency",
      width: 100,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "TOT_PREMIUM",
      columnName: "TotalPremium",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 100,
      minWidth: 150,
      maxWidth: 200,
    },

    {
      accessor: "SEC",
      columnName: "TypeOfSec",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Company",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 220,
      maxWidth: 350,
    },
    {
      accessor: "STATUS_DISP",
      columnName: "Status",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 160,
      maxWidth: 180,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "User",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 160,
      maxWidth: 180,
    },
  ],
};
