import { GridMetaDataType } from "@acuteinfo/common-base";
export const ParameterConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "PARA_NM",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    footerNote: "RightClickAcceptReject",
  },
  columns: [
    {
      accessor: "COMP_CD",
      columnName: "BankCode",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "PARA_CD",
      columnName: "Para Code",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "PARA_NM",
      columnName: "Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "PARA_VALUE",
      columnName: "New Para Value",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 70,
      maxWidth: 200,
    },
    {
      accessor: "OLD_VALUE",
      columnName: "Old Para Value",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 70,
      maxWidth: 200,
    },
    {
      accessor: "DATATYPE_DISP_VALUE",
      columnName: "New Datatype",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "OLD_DATATYPE_DISP_VALUE",
      columnName: "Old Datatype",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 120,
      maxWidth: 300,
    },
  ],
};
