import { GridMetaDataType } from "@acuteinfo/common-base";

export const LoanRescheduleGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "UNIQUE_ROWID",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 40, 60],
    defaultPageSize: 20,
    containerHeight: {
      min: "70vh",
      max: "70vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
    footerNote: "Double click to view details",
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 40,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "ACCT_NO",
      columnName: "Account Number",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Account Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "DISBURSEMENT_DT",
      columnName: "DisbursementDate",
      sequence: 3,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "DISBURSEMENT_AMT",
      columnName: "DisbursementAmount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 170,
      minWidth: 120,
      maxWidth: 200,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "INST_TYPE_DIS",
      columnName: "InstallmentType",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "INST_NO",
      columnName: "NoofInstallment",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "INS_START_DT",
      columnName: "InstallmentStartDate",
      sequence: 7,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 160,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "INST_RS",
      columnName: "DisburseInstallmentAmount",
      sequence: 8,
      alignment: "right",
      componentType: "currency",
      width: 200,
      minWidth: 120,
      maxWidth: 200,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "INT_RATE",
      columnName: "Interest Rate",
      sequence: 9,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 40,
      maxWidth: 150,
    },
    {
      accessor: "LOAN_DUE_DT",
      columnName: "Due Date",
      sequence: 10,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Maker",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 400,
      minWidth: 220,
      maxWidth: 700,
      showTooltip: true,
    },
    {
      accessor: "SR_CD",
      columnName: "Srcd",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
      isVisible: false,
    },
    {
      accessor: "UNIQUE_ROWID",
      columnName: "uniqueRowId",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
      isVisible: false,
    },
  ],
};
