import { GridMetaDataType } from "@acuteinfo/common-base";
export const TodayTransGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "TodayTransactionDetails",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 120,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "SR_NO",
      sequence: 1,
      componentType: "default",
      isAutoSequence: true,
      alignment: "right",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Time",
      accessor: "ENTERED_DATE",
      sequence: 2,
      componentType: "date",
      dateFormat: "hh:mm:ss a",
      alignment: "center",
      width: 120,
      maxWidth: 150,
      minWidth: 80,
    },
    {
      columnName: "ChequeNo",
      accessor: "CHEQUE_NO",
      sequence: 3,
      componentType: "default",
      width: 100,
      alignment: "right",
    },
    {
      columnName: "Trx",
      accessor: "TYPE_CD",
      sequence: 4,
      componentType: "default",
      alignment: "right",
      width: 70,
      maxWidth: 100,
      minWidth: 70,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 5,
      componentType: "default",
      showTooltip: true,
      width: 220,
    },
    {
      columnName: "CreditAmount",
      accessor: "CREDIT",
      sequence: 6,
      componentType: "currency",
      isDisplayTotal: true,
      totalDecimalCount: 2,
      width: 120,
      color: "green",
      alignment: "right",
    },

    {
      columnName: "DebitAmount",
      accessor: "DEBIT",
      sequence: 7,
      componentType: "currency",
      isDisplayTotal: true,
      totalDecimalCount: 2,
      width: 120,
      color: "red",
      alignment: "right",
    },
    {
      columnName: "VoucherNo",
      accessor: "TRAN_CD",
      sequence: 8,
      componentType: "default",
      alignment: "right",
      width: 120,
    },
    {
      columnName: "Status",
      accessor: "STATUS",
      sequence: 9,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "BranchCode",
      accessor: "ENTERED_BRANCH_CD",
      sequence: 10,
      componentType: "default",
      width: 105,
      maxWidth: 120,
      minWidth: 50,
    },
    {
      columnName: "Scroll",
      accessor: "SCROLL1",
      sequence: 11,
      componentType: "default",
      width: 100,
      maxWidth: 100,
      minWidth: 50,
      alignment: "right",
    },
    {
      columnName: "SDC",
      accessor: "SDC",
      sequence: 12,
      componentType: "default",
      width: 100,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Maker",
      accessor: "MAKER",
      sequence: 13,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Checker",
      accessor: "CHECKER",
      sequence: 14,
      componentType: "default",
      width: 120,
    },
  ],
};

export const AccountDetailsGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "AccountDetails",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 120,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: false,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "25.2vh",
      max: "25.2vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      columnName: "AcctHolderType",
      accessor: "ACCT_STATUS",
      sequence: 1,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "AccountNo",
      accessor: "AC_CD",
      sequence: 2,
      componentType: "default",
      width: 220,
    },
    {
      columnName: "Account_Name",
      accessor: "ACCT_NM",
      sequence: 3,
      componentType: "default",
      width: 300,
    },
    {
      columnName: "OpeningDate",
      accessor: "OP_DATE",
      sequence: 4,
      componentType: "date",
      width: 220,
    },
    {
      columnName: "STATUS",
      accessor: "ORG_STATUS",
      sequence: 5,
      componentType: "default",
      width: 130,
    },
    {
      columnName: "CloseDate",
      accessor: "CLOSE_DT",
      sequence: 6,
      componentType: "date",
      width: 220,
    },
  ],
};
