import { GridMetaDataType } from "@acuteinfo/common-base";

export const CreditWorthinessGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "CreditWorthiness",
    rowIdColumn: "ACCT_CD",
    defaultColumnConfig: {
      width: 350,
      minWidth: 100,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 30, 100],
    defaultPageSize: 15,
    containerHeight: {
      min: "50vh",
      max: "50vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 60,
      maxWidth: 150,
      isAutoSequence: true,
    },
    {
      accessor: "PURPOSE",
      columnName: "Purpose",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 130,
      maxWidth: 200,
      isDisplayTotal: true,
      footerIsMultivalue: true,
      setFooterValue(total, rows) {
        return "";
      },
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 130,
      maxWidth: 200,
      isDisplayTotal: true,
      footerIsMultivalue: true,
      setFooterValue(total, rows) {
        return "";
      },
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AccType",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 130,
      maxWidth: 200,
      isDisplayTotal: true,
      footerIsMultivalue: true,
      setFooterValue(total, rows) {
        return "";
      },
    },
    {
      accessor: "ACCT_CD",
      columnName: "ACNo",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 70,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AcctHolder",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 500,
      showTooltip: true,
    },
    {
      accessor: "IR_AMOUNT",
      columnName: "IRBalance",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 90,
      maxWidth: 190,
      showTooltip: true,
      isDisplayTotal: true,
      footerIsMultivalue: true,
      setFooterValue(total, rows) {
        return "";
      },
    },
    {
      accessor: "AMOUNT",
      columnName: "Balance",
      sequence: 8,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 90,
      maxWidth: 190,
      showTooltip: true,
    },
    {
      accessor: "CLOSE_DT",
      columnName: "CloseDate",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 170,
    },
    {
      accessor: "LIMIT_AMOUNT",
      columnName: "Limit",
      sequence: 10,
      alignment: "right",
      componentType: "currency",
      isDisplayTotal: true,
      totalDecimalCount: 2,
      width: 120,
      minWidth: 90,
      maxWidth: 190,
      showTooltip: true,
    },
    {
      accessor: "SANCTION_DT",
      columnName: "SanDate",
      sequence: 11,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 170,
      minWidth: 130,
      maxWidth: 200,
      isDisplayTotal: true,
      footerIsMultivalue: true,
      setFooterValue(total, rows) {
        return "";
      },
    },
    {
      accessor: "INST_DUE_DT",
      columnName: "DueDate",
      sequence: 12,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "LAST_OVERDUE",
      columnName: "LastOverDue",
      sequence: 13,
      alignment: "right",
      componentType: "currency",
      width: 110,
      minWidth: 90,
      maxWidth: 180,
      showTooltip: true,
    },
    {
      accessor: "WRITE_OFF_DTL",
      columnName: "WriteOffDetails",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "STATUS_DISP",
      columnName: "Status",
      sequence: 15,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 70,
      maxWidth: 150,
    },
  ],
};
