import { GridMetaDataType } from "@acuteinfo/common-base";

export const PTSGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "PTSCodeEntry",
    rowIdColumn: "U_ID",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: false,
    containerHeight: {
      min: "40vh",
      max: "40vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
    disableGlobalFilter: true,
    hideFooter: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 150,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "WEF",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 110,
      minWidth: 90,
      maxWidth: 170,
    },
    {
      accessor: "COLUMN_NM",
      columnName: "Column",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "DISP_VAL",
      columnName: "Value",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "DOC_STATUS",
      columnName: "Active",
      sequence: 5,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 90,
      minWidth: 70,
      maxWidth: 140,
      defaultValue: false,
      isReadOnly: (initialValue, original, prevRows, nextRows) => {
        if (original?.ALLOW_EDIT === "Y") {
          return false;
        }
        return true;
      },
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 6,
      alignment: "left",
      componentType: "editableTextField",
      width: 350,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "COLUMN_VAL",
      columnName: "Value",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
      isVisible: false,
    },
    {
      accessor: "U_ID",
      columnName: "unique ID",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
      isVisible: false,
    },
  ],
};

export const PriorityGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "PriorityMiscellaneous",
    rowIdColumn: "U_ID",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: false,
    containerHeight: {
      min: "40vh",
      max: "40vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
    disableGlobalFilter: true,
    hideFooter: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 150,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "WEF",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 110,
      minWidth: 90,
      maxWidth: 170,
    },
    {
      accessor: "PARENT_CD",
      columnName: "Parent",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "PRIO_CD",
      columnName: "Priority",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "SUB_PRIORITY_CD",
      columnName: "SubPriority",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "DOC_STATUS",
      columnName: "Active",
      sequence: 5,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 90,
      minWidth: 70,
      maxWidth: 140,
      defaultValue: false,
      isReadOnly: (initialValue, original, prevRows, nextRows) => {
        if (original?.ALLOW_EDIT === "Y") {
          return false;
        }
        return true;
      },
    },
    {
      accessor: "COLUMN_VAL",
      columnName: "Value",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
      isVisible: false,
    },
    {
      accessor: "U_ID",
      columnName: "unique ID",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
      isVisible: false,
    },
  ],
};
