import { GridMetaDataType } from "@acuteinfo/common-base";

export const LetterOfContinuityGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Letter Of Countinuity Detail",
    rowIdColumn: "SR_CD_ID_NO",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    hideFooter: true,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: {
      min: "45vh",
      max: "45vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
    disableGlobalFilter: true,
    hiddenFlag: "_hidden",
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 60,
      maxWidth: 150,
      isAutoSequence: true,
    },
    {
      accessor: "LETTER_DP_FLAG",
      columnName: "EntryType",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "LC_START_DT",
      columnName: "Start Date",
      sequence: 3,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "LC_PERIOD_CD",
      columnName: "Period",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "LC_PERIOD_NO",
      columnName: "Days", /// Change lebal according to Period
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "LC_DUE_DT",
      columnName: "DueDate",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "DOC_VALUE",
      columnName: "DocumentValue",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      columnName: "Action",
      componentType: "deleteRowCell",
      accessor: "_hidden",
      sequence: 7,
      width: 90,
      alignment: "center",
      maxWidth: 120,
      minWidth: 90,
      shouldExclude: (initialValue, original) => {
        if (Boolean(original?.IsNewRow)) {
          return false;
        }
        return true;
      },
    },
    {
      accessor: "SR_CD_ID_NO",
      columnName: "SRNO",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      isVisible: false,
    },
  ],
};
