import { GridMetaDataType } from "@acuteinfo/common-base";
import { getHoldChargeDropDown } from "./api";
export const HoldChargeGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Hold Charge",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 50,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
      isAutoSequence: true,
    },
    {
      columnName: "Drtype",
      accessor: "ACCT_TYPE",
      sequence: 2,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "DrACNo",
      accessor: "ACCT_CD",
      sequence: 3,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Crbr",
      accessor: "TO_BRANCH_CD",
      sequence: 4,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Crtype",
      accessor: "TO_ACCT_TYPE",
      sequence: 5,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "CrAcNoShort",
      accessor: "TO_ACCT_CD",
      sequence: 6,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "HoldDate",
      accessor: "ENTERED_DATE",
      sequence: 7,
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      alignment: "center",
      width: 100,
    },
    {
      columnName: "Trx",
      accessor: "TYPE_CD",
      sequence: 8,
      componentType: "default",
      alignment: "right",
      width: 50,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 9,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      columnName: "Amount",
      accessor: "AMOUNT",
      sequence: 10,
      componentType: "currency",
      width: 100,
      alignment: "right",
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      columnName: "PaidWaive",
      accessor: "PAID",
      sequence: 11,
      componentType: "editableSelect",
      options: getHoldChargeDropDown,
      _optionsKey: "HoldChargeDropDown",
      width: 100,
      __VIEW__: {
        isReadOnly: true,
      },
    },
    {
      accessor: "PROCESS",
      columnName: "",
      componentType: "icondefault",
      buttonLabel: "Open",
      sequence: 12,
      alignment: "center",
      width: 80,
      minWidth: 70,
      maxWidth: 100,
      isImageURL: true,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.FLAG === "Y") {
          return false;
        } else {
          return true;
        }
      },
    },
    {
      columnName: "EntBr",
      accessor: "ENTERED_BRANCH_CD",
      sequence: 13,
      componentType: "default",
      width: 80,
    },
  ],
};
