import { GridMetaDataType } from "@acuteinfo/common-base";
export const TRN001_TableMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 350,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "30vh",
      max: "30vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    hideHeader: false,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "ACCT_CD",
      columnName: "ACNumber",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "ChequeNo",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "SCROLL1",
      columnName: "Scroll",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "SDC_DESC",
      columnName: "SDC",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "TRX_DESC",
      columnName: "Trx",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "ACCT_TYPE_DESC",
      columnName: "AccType",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "Voucher No",
      sequence: 1,
      componentType: "default",
      width: 80,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch",
      sequence: 2,
      componentType: "default",
      width: 60,
    },
    {
      accessor: "ACCT_TYPE_DESC",
      columnName: "AcctType",
      sequence: 3,
      componentType: "default",
      width: 200,
    },
    {
      accessor: "ACCT_CD",
      columnName: "AccountNo",
      sequence: 4,
      componentType: "default",
      width: 80,
    },
    {
      accessor: "TRX_DESC",
      columnName: "Trx",
      sequence: 5,
      componentType: "default",
      width: 80,
    },
    {
      accessor: "SCROLL1",
      columnName: "Scroll/Token",
      sequence: 6,
      componentType: "default",
      width: 50,
    },
    {
      accessor: "SDC_DESC",
      columnName: "SDC",
      sequence: 7,
      componentType: "default",
      width: 100,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 8,
      componentType: "default",
      showTooltip: true,
      width: 130,
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "ChequeNo",
      sequence: 9,
      width: 70,
      componentType: "default",
    },
    {
      accessor: "L_INST_DT",
      columnName: "ChequeDate",
      sequence: 9,
      width: 130,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "EnteredDate",
      sequence: 10,
      width: 130,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
    },
    {
      accessor: "DEBIT",
      columnName: "Debit",
      sequence: 11,
      componentType: "currency",
      color: "red",
      width: 90,
      isDisplayTotal: true,
    },
    {
      accessor: "CREDIT",
      columnName: "Credit",
      sequence: 12,
      componentType: "currency",
      color: "green",
      isDisplayTotal: true,
      width: 90,
    },
  ],
};
