import { GridMetaDataType } from "@acuteinfo/common-base";

export const fdDetailGridData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "FDDetail",
    rowIdColumn: "FD_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "58vh",
      max: "58vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "ACCOUNT_NUMBER",
      columnName: "AccountNum",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 125,
      minWidth: 100,
      maxWidth: 140,
    },
    {
      accessor: "FD_NO",
      columnName: "FDNo",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 85,
      minWidth: 70,
      maxWidth: 150,
    },
    {
      accessor: "DEPOSITE_DATE",
      columnName: "DepositeDate",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "MATURITY_AMT",
      columnName: "MaturityAmount",
      sequence: 5,
      alignment: "right",
      isDisplayTotal: true,
      componentType: "currency",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "PRINCIPAL_AMT",
      columnName: "PrincipalAmount",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      isDisplayTotal: true,
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      isVisible: true,
    },
    {
      accessor: "MATURITY_DATE",
      columnName: "MaturityDate",
      sequence: 7,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 152,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "RATE",
      columnName: "Rate",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 55,
      minWidth: 50,
      maxWidth: 80,
    },
    {
      accessor: "ISSUE_DATE",
      columnName: "IssueDate",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 104,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "BALANCE_AMT",
      columnName: "BalanceAmount",
      sequence: 10,
      alignment: "right",
      componentType: "currency",
      isDisplayTotal: true,
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};
