import { GridMetaDataType } from "@acuteinfo/common-base";
export const TodaysTransactionTableGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "TodaysTransaction",
    rowIdColumn: "TRAN_CD",

    defaultColumnConfig: {
      width: 200,
      maxWidth: 300,
      minWidth: 200,
    },

    allowColumnReordering: false,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 40, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "50vh",
      max: "50vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hideFooter: false,
  },
  columns: [
    {
      accessor: "sr_no",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 65,
      minWidth: 65,
      maxWidth: 130,
      isAutoSequence: true,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "BrCode",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 90,
      minWidth: 45,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AcctType",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 240,
    },
    {
      accessor: "ACCT_CD",
      columnName: "ACNo",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 40,
      maxWidth: 200,
    },
    {
      accessor: "TRAN_DT",
      columnName: "TrnDate",
      sequence: 5,
      alignment: "left",
      componentType: "date",
      // dateFormat: "dd/MM/yyyy",
      width: 90,
      minWidth: 60,
      maxWidth: 260,
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "Chequeno",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 90,
      minWidth: 90,
      maxWidth: 200,
    },
    {
      accessor: "TYPE_CD",
      columnName: "Trx",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 200,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "DEBIT",
      columnName: "DebitAmount",
      sequence: 5,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 100,
      maxWidth: 220,
      color: "red",
      isDisplayTotal: true,
      totalDecimalCount: 2,
      // currencyRefColumn: "CURR_CD",
      // symbolPosi: "end",
    },
    {
      accessor: "CREDIT",
      columnName: "CreditAmount",
      sequence: 5,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 100,
      maxWidth: 220,
      color: "green",
      isDisplayTotal: true,
      totalDecimalCount: 2,
      // currencyRefColumn: "CURR_CD",
      // isCurrencyCode: true,
      // symbolPosi: "end",
    },
    {
      accessor: "TRAN_CD",
      columnName: "Vno",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 160,
      maxWidth: 220,
    },
    {
      accessor: "CONFIRMED",
      columnName: "STATUS",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 160,
      maxWidth: 220,
    },
    {
      accessor: "SCROLL1",
      columnName: "Scroll",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 160,
      maxWidth: 220,
    },
    {
      accessor: "SDC",
      columnName: "SDC",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 160,
      maxWidth: 220,
    },
    {
      accessor: "MAKER",
      columnName: "Maker",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 160,
      maxWidth: 220,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "MakerTime",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      dateFormat: "hh:mm:ss a",
      width: 140,
      minWidth: 160,
      maxWidth: 220,
    },
    {
      accessor: "CHECKER",
      columnName: "Checker",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 160,
      maxWidth: 220,
    },
    {
      accessor: "VERIFIED_DATE",
      columnName: "CheckerTime",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      dateFormat: "hh:mm:ss a",
      width: 140,
      minWidth: 160,
      maxWidth: 220,
    },
  ],
};
