export const UserProfileMetaData = {
  form: {
    name: "user-profile",
    label: "UserProfile",
    resetFieldOnUnmount: false,
    validationRun: "onBlur",
    render: {
      ordering: "auto",
      renderType: "simple",
      gridConfig: {
        item: {
          xs: 12,
          sm: 3,
          md: 3,
        },
        container: {
          direction: "row",
          spacing: 1.5,
        },
      },
    },
    componentProps: {
      datePicker: {
        fullWidth: true,
      },
      select: {
        fullWidth: true,
      },
      textField: {
        fullWidth: true,
      },
      numberFormat: {
        fullWidth: true,
      },
    },
  },
  fields: [
    {
      render: { componentType: "textField", group: 0 },
      name: "USER_ID",
      sequence: 1,
      type: "text",
      label: "UserID",
      isReadOnly: true,
      fullWidth: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "GROUP_NAME",
      sequence: 6,
      type: "text",
      label: "UserGroup",
      isReadOnly: true,
      fullWidth: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },

    {
      render: { componentType: "phoneNumber", group: 0 },
      name: "MOBILE_NUMBER",
      sequence: 4,
      type: "text",
      label: "MobileNo",
      isReadOnly: true,
      fullWidth: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "CUSTOMER_ID",
      sequence: 8,
      type: "text",
      label: "CustomerId",
      fullWidth: true,
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "DEFAULT_BRANCH",
      sequence: 8,
      type: "text",
      label: "DefaultBranch",
      fullWidth: true,
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 3,
        sm: 3,
        lg: 3,
        xl: 3,
      },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "EMP_ID",
      sequence: 8,
      type: "text",
      label: "EmployeeId",
      fullWidth: true,
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "EMAIL_ID",
      sequence: 8,
      type: "text",
      fullWidth: true,
      label: "EmailId",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },
    {
      render: { componentType: "datetimePicker", group: 0 },
      name: "LAST_FAILED_LOGIN",
      sequence: 8,
      fullWidth: true,
      format: "dd/MM/yyyy HH:mm:ss",
      label: "profile.LastUnsuccessfullLogin",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },
    {
      render: { componentType: "checkbox", group: 0 },
      name: "ALLOW_RELEASE",
      sequence: 9,
      fullWidth: true,
      type: "text",
      label: "AllowedRelease",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },
    {
      render: { componentType: "checkbox", group: 0 },
      name: "VIEW_SIGNATURE",
      sequence: 9,
      type: "text",
      fullWidth: true,
      label: "Signature",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 2.25,
        sm: 2.25,
        lg: 2.25,
        xl: 2.25,
      },
    },
    {
      render: {
        componentType: "typography",
      },
      name: "CIBVILEW",
      fullWidth: true,
      label: "DebitTransactionLimit",
      defaultValue: "Debit Transaction Limit",
      TypographyProps: { variant: "h6" },
      GridProps: {
        xs: 12,
        md: 12,
        sm: 12,
        lg: 12,
        xl: 12,
      },
    },

    {
      render: { componentType: "amountField", group: 0 },
      name: "DR_CASE_LIMIT",
      fullWidth: true,
      sequence: 8,
      type: "text",
      label: "CashwithdrawalLimit",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 3,
        sm: 3,
        lg: 3,
        xl: 3,
      },
    },

    {
      render: { componentType: "amountField", group: 0 },
      name: "DR_CLEARING_LIMIT",
      sequence: 8,
      type: "text",
      label: "ClearingLimit",
      fullWidth: true,
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 3,
        sm: 3,
        lg: 3,
        xl: 3,
      },
    },

    {
      render: { componentType: "amountField", group: 0 },
      fullWidth: true,
      name: "DR_TRANSFER_LIMIT",
      sequence: 8,
      type: "text",
      label: "TransferLimit",
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 3,
        sm: 3,
        lg: 3,
        xl: 3,
      },
    },
    {
      render: {
        componentType: "typography",
      },
      name: "CIBVEW",
      fullWidth: true,
      label: "",
      defaultValue: "Credit Transaction Limit",
      TypographyProps: { variant: "h6" },
      GridProps: {
        xs: 12,
        md: 12,
        sm: 12,
        lg: 12,
        xl: 12,
      },
    },
    {
      render: { componentType: "amountField", group: 0 },
      name: "CR_CASE_LIMIT",
      sequence: 8,
      type: "text",
      label: "CashRecieptLimit",
      fullWidth: true,
      isReadOnly: true,
      GridProps: {
        xs: 12,
        md: 3,
        sm: 3,
        lg: 3,
        xl: 3,
      },
    },
    {
      render: { componentType: "amountField", group: 0 },
      name: "CR_CLEARING_LIMIT",
      sequence: 8,
      type: "text",
      label: "ClearingLimit",
      isReadOnly: true,
      fullWidth: true,
      GridProps: {
        xs: 12,
        md: 3,
        sm: 3,
        lg: 3,
        xl: 3,
      },
    },
    {
      render: { componentType: "amountField", group: 0 },
      name: "CR_TRANSFER_LIMIT",
      sequence: 8,
      type: "text",
      label: "TransferLimit",
      isReadOnly: true,
      fullWidth: true,
      validate: "getValidateValue",
      GridProps: {
        xs: 12,
        md: 3,
        sm: 3,
        lg: 3,
        xl: 3,
      },
    },
  ],
};
