import { GridMetaDataType } from "@acuteinfo/common-base";

export const UserLoginDtlGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "UserLoginDetails",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    hideFooter: true,
    disableGroupBy: true,
    enablePagination: false,
    disableGlobalFilter: true,
    containerHeight: {
      min: "calc(100vh - 400px)",
      max: "calc(100vh - 500px)",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "USERNAME",
      columnName: "LoginID",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 90,
      minWidth: 60,
      maxWidth: 100,
    },
    {
      accessor: "LOGIN_DT",
      columnName: "LoginDate",
      sequence: 3,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 140,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "USER_FLAG",
      columnName: "LoginFlag",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "LOGOUT_DT",
      columnName: "LogoutDate",
      sequence: 5,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 140,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "REMARKS",
      columnName: "ActivityRemarks",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "IP_ADDR",
      columnName: "IPAddress",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "RELEASED_USER_NAME",
      columnName: "ReleasedUser",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 145,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "RELEASED_DT",
      columnName: "ReleasedDate",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 140,
      minWidth: 100,
      maxWidth: 150,
    },
  ],
};
