import { GridMetaDataType } from "@acuteinfo/common-base";

export const RetrieveGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "38vh",
      max: "38vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "PAYSLIP_NO",
      columnName: "Playslip No",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "DD_STATUS",
      columnName: "Status",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 180,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Date",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      width: 150,
      minWidth: 120,
      maxWidth: 180,
    },
    {
      accessor: "AMOUNT",
      columnName: "Amount",
      alignment: "left",
      sequence: 3,
      componentType: "currency",
      width: 150,
      minWidth: 120,
      maxWidth: 180,
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "Chequeno",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      accessor: "INFAVOUR_OF",
      columnName: "Infavour of",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 150,
      maxWidth: 150,
    },
  ],
};
