import { GridMetaDataType } from "@acuteinfo/common-base";
export const TempGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "TempODAgainst",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      alignment: "right",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "FromEffDate",
      accessor: "FROM_EFF_DATE",
      sequence: 3,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 80,
    },
    {
      columnName: "ToEffDate",
      accessor: "TO_EFF_DATE",
      sequence: 4,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 80,
    },
    {
      columnName: "CodeDescription",
      accessor: "CODE_DESC",
      sequence: 5,
      componentType: "default",
      showTooltip: true,
      width: 185,
    },
    {
      columnName: "AmountUpTo",
      accessor: "AMOUNT_UPTO",
      sequence: 6,
      componentType: "currency",
      isDisplayTotal: true,
      alignment: "right",
      width: 120,
    },
    {
      columnName: "Active",
      accessor: "FLAG_DISP",
      sequence: 7,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "EnteredBy",
      accessor: "ENTERED_BY",
      sequence: 8,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "Confirmed",
      accessor: "CONFIRMED",
      sequence: 9,
      componentType: "default",
      width: 80,
    },
    {
      columnName: "LastMachineName",
      accessor: "LAST_MACHINE_NM",
      sequence: 10,
      componentType: "default",
      showTooltip: true,
      width: 145,
    },
  ],
};
