import { GridMetaDataType } from "@acuteinfo/common-base";
export const InstructionGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "SpInstruction",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "SR_NO",
      sequence: 1,
      componentType: "default",
      alignment: "right",
      isAutoSequence: true,
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      accessor: "AC_NO",
      columnName: "MainAc",
      sequence: 2,
      componentType: "default",
      alignment: "right",
      width: 150,
    },
    {
      accessor: "ACCT_NM",
      columnName: "MainAcName",
      sequence: 3,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      accessor: "OTH_AC_NO",
      columnName: "OtherAc",
      sequence: 4,
      componentType: "default",
      alignment: "right",
      width: 150,
    },

    {
      accessor: "OTH_ACCT_NM",
      columnName: "OtherAcName",
      sequence: 5,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      accessor: "SP_NM",
      columnName: "Instruction",
      sequence: 6,
      componentType: "default",
      showTooltip: true,
      width: 150,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 7,
      componentType: "default",
      showTooltip: true,
      width: 150,
    },
    {
      accessor: "TYPE_CD_DISP",
      columnName: "Type",
      sequence: 8,
      componentType: "default",
      width: 120,
    },

    {
      accessor: "AMOUNT",
      columnName: "Amount",
      sequence: 9,
      componentType: "currency",
      alignment: "right",
      width: 150,
    },

    {
      accessor: "EFFECTIVE_DT",
      columnName: "EffectiveDate",
      sequence: 10,
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      alignment: "center",
      width: 100,
    },
  ],
};
