import { GridMetaDataType } from "@acuteinfo/common-base";
export const ParametersGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "PARA_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    footerNote: "Parameters In Red Colour Indicates Pending For Confirmation",
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      isAutoSequence: true,
      width: 80,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "PARA_CD",
      columnName: "Code",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "PARA_NM",
      columnName: "Description",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 400,
      minWidth: 200,
      maxWidth: 600,
    },
    {
      accessor: "DATATYPE_DISP_VALUE",
      columnName: "Datatype",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "PARA_VALUE",
      columnName: "Value",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 250,
      maxWidth: 300,
    },
    {
      columnName: "Change History",
      componentType: "buttonRowCell",
      accessor: "SIGN_PATH",
      sequence: 4,
      buttonLabel: "...",
      isVisible: true,
      width: 120,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 250,
      maxWidth: 300,
    },
    {
      accessor: "CONFIRMED_STATUS",
      columnName: "status",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      color: (val, data) => {
        let confirmed = data?.original?.CONFIRMED ?? "";
        return confirmed === "N"
          ? "inherit"
          : confirmed === "R"
          ? "rgb(128, 0, 0)"
          : "inherit";
      },
      width: 230,
      minWidth: 220,
      maxWidth: 300,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "ModifiedDateTime",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
  ],
};
export const AuditMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "OLD_VALUE",
      columnName: "OldValue",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "NEW_VALUE",
      columnName: "NewValue",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "MODIFIED_BY",
      columnName: "ModifiedBy",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "MODIFIED_DATE",
      columnName: "ModifiedDateTime",
      sequence: 4,
      alignment: "left",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      componentType: "date",
      width: 150,
      minWidth: 120,
      maxWidth: 180,
    },
    {
      accessor: "MACHINE_NM",
      columnName: "ModifiedMachineName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "VerifiedBy",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "VERIFIED_DATE",
      columnName: "VerifiedDate",
      sequence: 5,
      alignment: "left",
      dateFormat: "dd/MM/yyyy hh:mm:ss",
      componentType: "default",
      width: 150,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "VERIFIED_MACHINE_NM",
      columnName: "VerifiedMachineName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 200,
    },
  ],
};
