import { GridMetaDataType } from "@acuteinfo/common-base";
export const CheckBookGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ChequeBook Details",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "36vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "sr",
      columnName: "Sr.",
      sequence: 1,
      componentType: "default",
      width: 60,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Issue Date",
      sequence: 2,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      accessor: "AUTO_CHQBK_FLAG",
      columnName: "Auto Issue",
      sequence: 3,
      componentType: "default",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      accessor: "CHEQUE_FROM",
      columnName: "From CHQ No.",
      sequence: 4,
      componentType: "default",
      width: 120,
      alignment: "right",
    },
    {
      accessor: "CHEQUE_TO",
      columnName: "To CHQ No.",
      sequence: 5,
      componentType: "default",
      width: 120,
      alignment: "right",
    },
    {
      accessor: "CHEQUE_TOTAL",
      columnName: "No. of CHQ(s) ",
      sequence: 6,
      componentType: "default",
      width: 90,
      maxWidth: 100,
      minWidth: 50,
      alignment: "right",
    },
    {
      accessor: "SERVICE_TAX",
      columnName: "Charge",
      sequence: 7,
      componentType: "currency",
      width: 120,
      alignment: "right",
    },
    {
      accessor: "AMOUNT",
      columnName: "GST",
      sequence: 8,
      componentType: "currency",
      width: 120,
      alignment: "right",
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 9,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "CHARACTERISTICS",
      columnName: "Characteristics",
      sequence: 10,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "PAYABLE_AT_PAR",
      columnName: "At Par",
      sequence: 11,
      componentType: "default",
      width: 120,
    },
    {
      accessor: "REQUISITION_DT",
      columnName: "Requisition",
      sequence: 12,
      componentType: "date",
      isVisible: true,
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      accessor: "UNUSED_CHQ",
      columnName: "Pending",
      sequence: 13,
      componentType: "default",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
      alignment: "right",
    },
  ],
};
