import { GridMetaDataType } from "@acuteinfo/common-base";
export const multipleChequebookGridData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ChequeBookSeriesDetail",
    rowIdColumn: "CHEQUE_FROM",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    disableGlobalFilter: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "50vh",
      max: "50vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "CHEQUE_FROM",
      columnName: "FromChequeNo",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 139,
      minWidth: 100,
      maxWidth: 160,
      isVisible: true,
    },
    {
      accessor: "CHEQUE_TO",
      columnName: "ToChequeNo",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 123,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "CHEQUE_TOTAL",
      columnName: "NoOfCheques",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 138,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "AMOUNT",
      columnName: "ServiceCharge",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 108,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "SERVICE_TAX",
      columnName: "GST",
      sequence: 8,
      alignment: "right",
      componentType: "currency",
      width: 105,
      minWidth: 100,
      maxWidth: 130,
    },
  ],
};
