import { GridMetaDataType } from "@acuteinfo/common-base";
export const issuedChequeBkGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ChequeBkAlreadyIssued",
    rowIdColumn: "CHEQUE_NO",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: false,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "35vh",
      max: "35vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "TRAN_DT",
      columnName: "IssueDate",
      sequence: 1,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 102,
      minWidth: 900,
      maxWidth: 130,
    },

    {
      accessor: "CHEQUE_FROM",
      columnName: "FromChequeNo",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      width: 139,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "CHEQUE_TO",
      columnName: "ToChequeNo",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 128,
      minWidth: 100,
      maxWidth: 140,
    },
    {
      accessor: "CHEQUE_TOTAL",
      columnName: "NoOfCheques",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      width: 136,
      minWidth: 100,
      maxWidth: 150,
    },

    {
      accessor: "AMOUNT",
      columnName: "ServiceCharge",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 109,
      minWidth: 80,
      maxWidth: 130,
    },
    {
      accessor: "CONFIRMED_DISPLAY",
      columnName: "Status",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 80,
      minWidth: 60,
      maxWidth: 100,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "REQUISITION_DT",
      columnName: "RequisitionDate",
      sequence: 8,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 133,
      minWidth: 100,
      maxWidth: 150,
    },
  ],
};
