import { GridMetaDataType } from "@acuteinfo/common-base";
export const RecurringPaymentEntryGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 30, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "55vh",
      max: "55vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 50,
      maxWidth: 150,
      isAutoSequence: true,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "Branch",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 40,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AccountType",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_CD",
      columnName: "AccountNum",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "ACCT_NM",
      columnName: "accountName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 310,
      minWidth: 300,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "TDS_AMT",
      columnName: "CalcTDS",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 120,
      minWidth: 110,
      maxWidth: 130,
    },
    {
      accessor: "TRF_AMT",
      columnName: "Transfer",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
      isDisplayTotal: true,
    },
    {
      accessor: "TOKEN_NO",
      columnName: "CashPaymentTokenNo",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 180,
      minWidth: 160,
      maxWidth: 250,
    },
    {
      accessor: "CASH_AMT",
      columnName: "Cash",
      sequence: 9,
      alignment: "right",
      componentType: "currency",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
      isDisplayTotal: true,
    },
    {
      accessor: "PAYSLIP",
      columnName: "ByPayslipDD",
      sequence: 10,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 100,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      accessor: "RTGS_NEFT",
      columnName: "ByNEFT",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 100,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      accessor: "PAYMENT_AMT",
      columnName: "PaymentAmount",
      sequence: 12,
      alignment: "right",
      componentType: "currency",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
      isDisplayTotal: true,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Maker",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "MakerTime",
      sequence: 14,
      alignment: "center",
      componentType: "date",
      dateFormat: "hh:mm:ss a",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Checker",
      sequence: 15,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "CheckerTime",
      sequence: 16,
      alignment: "center",
      componentType: "date",
      dateFormat: "hh:mm:ss a",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "CONF_STATUS",
      columnName: "ConfStatus",
      sequence: 17,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
  ],
};
