import { GridMetaDataType } from "@acuteinfo/common-base";

export const ClearingBankMstGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "BANK_CD",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [30, 50, 100],
    defaultPageSize: 30,
    containerHeight: {
      min: "70vh",
      max: "70vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "RBI_CD",
      columnName: "RBICode",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 150,
      maxWidth: 190,
    },
    {
      accessor: "BANK_CD",
      columnName: "Code",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 150,
      maxWidth: 190,
    },
    {
      accessor: "BANK_NM",
      columnName: "BankName",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 360,
      minWidth: 300,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "EXCLUDE",
      columnName: "Exclude",
      sequence: 5,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 120,
      minWidth: 100,
      maxWidth: 180,
      isReadOnly: true,
    },
    {
      accessor: "CTS",
      columnName: "CTS",
      sequence: 6,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 120,
      minWidth: 100,
      maxWidth: 180,
      isReadOnly: true,
    },
  ],
};
