import { GridMetaDataType } from "@acuteinfo/common-base";
export const GroupGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Group",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      alignment: "right",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "CustomerId",
      accessor: "CUSTOMER_ID",
      sequence: 2,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "GroupName",
      accessor: "DESCR",
      sequence: 3,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "Branch",
      accessor: "BRANCH_CD",
      sequence: 4,
      componentType: "default",
      alignment: "right",
      width: 50,
    },
    {
      columnName: "type",
      accessor: "ACCT_TYPE",
      sequence: 5,
      componentType: "default",
      alignment: "right",
      width: 50,
    },
    {
      columnName: "ACNo",
      accessor: "ACCT_CD",
      sequence: 6,
      componentType: "default",
      alignment: "right",
      width: 100,
    },
    {
      columnName: "Account_Name",
      accessor: "ACCT_NM",
      sequence: 7,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      columnName: "Balance",
      accessor: "WITHDRAWLBAL",
      sequence: 8,
      componentType: "currency",
      alignment: "right",
      isDisplayTotal: true,
      totalDecimalCount: 2,
      width: 100,
    },
    {
      columnName: "LimitAmount",
      accessor: "LIMIT_AMOUNT",
      sequence: 9,
      componentType: "currency",
      alignment: "right",
      isDisplayTotal: true,
      totalDecimalCount: 2,
      width: 100,
    },
    {
      columnName: "overdue",
      accessor: "OVERDUE",
      sequence: 10,
      componentType: "currency",
      alignment: "right",
      isDisplayTotal: true,
      totalDecimalCount: 2,
      width: 100,
    },
    {
      columnName: "Status",
      accessor: "STATUS",
      sequence: 11,
      componentType: "default",
      width: 100,
    },
  ],
};
