import { GridMetaDataType } from "@acuteinfo/common-base";
export const ATMGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ATM",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      alignment: "right",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "IssueFromBranch",
      accessor: "ISSUE_BRANCH_CD",
      sequence: 2,
      componentType: "default",
      width: 145,
    },
    {
      columnName: "RequestDate",
      accessor: "REQ_DT",
      sequence: 3,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "IssueDate",
      accessor: "ISSUE_DT",
      sequence: 4,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "CardNo",
      accessor: "CARD_NO",
      sequence: 5,
      componentType: "default",
      width: 165,
    },
    {
      columnName: "CardType",
      accessor: "CARD_TYPE",
      sequence: 6,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "ExpireDate",
      accessor: "EXPIRE_DT",
      sequence: 7,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 8,
      componentType: "default",
      width: 200,
      showTooltip: true,
    },
    {
      columnName: "Status",
      accessor: "STATUS_DISP",
      sequence: 9,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "Deactivedate",
      accessor: "DEACTIVE_DT",
      sequence: 10,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "Reason",
      accessor: "REASON",
      sequence: 11,
      componentType: "default",
      showTooltip: true,
      width: 120,
    },
    {
      columnName: "ChargeApplicable",
      accessor: "CHARG_FLAG",
      sequence: 12,
      componentType: "default",
      width: 135,
    },
    {
      columnName: "ChargeAmount",
      accessor: "CHARGE_AMT",
      sequence: 13,
      componentType: "currency",
      alignment: "right",
      width: 150,
    },
    {
      columnName: "SMSAlert",
      accessor: "SMS_ALERT",
      sequence: 14,
      componentType: "default",
      width: 120,
    },
  ],
};
