import { GridMetaDataType } from "@acuteinfo/common-base";

export const searchLockerNoGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Search Account Master",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowColumnHiding: false,
    disableGlobalFilter: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "LOCKER_NO",
      columnName: "lockerNumber",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "LOC_SIZE_CD",
      columnName: "",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 50,
      minWidth: 50,
      maxWidth: 50,
    },
    {
      accessor: "SIZE_NM",
      columnName: "lockerSize",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 110,
    },
    {
      accessor: "LOCKER_KEY_NO",
      columnName: "keyNumber",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AcctType",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "LST_ACCT_CD",
      columnName: "ACNo",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ACCT_NM",
      columnName: "accountName",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "DUE_DT_START",
      columnName: "rentDueStart",
      sequence: 8,
      alignment: "center",
      componentType: "date",
      width: 250,
      minWidth: 100,
      maxWidth: 500,
    },
  ],
};
