import { GridMetaDataType } from "@acuteinfo/common-base";

export const todayTrnsGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 100,
      maxWidth: 100,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 35],
    defaultPageSize: 15,
    containerHeight: {
      min: "40vh",
      max: "40vh",
    },
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      isAutoSequence: true,
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "RECEIPT_NO",
      columnName: "receiptNoL",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "TRAN_DT",
      columnName: "TranDate",
      sequence: 3,
      alignment: "center",
      componentType: "date",
      width: 120,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "AMOUNT",
      columnName: "rentAmt",
      sequence: 4,
      alignment: "center",
      componentType: "default",
      isReadOnly: true,
      width: 110,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "SERVICE_TAX_AMT",
      columnName: "GST",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "TRAN_CD",
      columnName: "VoucherNo",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
      showTooltip: true,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 8,
      alignment: "center",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "RENT_PERIOD",
      columnName: "Period",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "DELETE",
      columnName: "",
      componentType: "buttonRowCell",
      buttonLabel: "delete",
      sequence: 10,
      alignment: "center",
      width: 80,
      minWidth: 70,
      maxWidth: 100,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.ALLOW_DELETE === "Y") {
          return false;
        } else {
          return true;
        }
      },
    },
  ],
};
