import { GridMetaDataType } from "@acuteinfo/common-base";

export const viewTrnsGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 100,
      maxWidth: 100,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 35],
    defaultPageSize: 15,
    containerHeight: {
      min: "40vh",
      max: "40vh",
    },
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      isAutoSequence: true,
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "TRAN_DT",
      columnName: "TranDate",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      width: 120,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AccType",
      sequence: 3,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_CD",
      columnName: "ACNo",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      isReadOnly: true,
      width: 110,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "TYPE_CD",
      columnName: "TransactionType",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 120,
      maxWidth: 300,
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "receiptNo",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
      showTooltip: true,
    },
    {
      accessor: "AMOUNT",
      columnName: "amount",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 160,
      minWidth: 100,
      maxWidth: 250,
      showTooltip: true,
    },
  ],
};
