import { GridMetaDataType } from "@acuteinfo/common-base";

export const FDSchemeGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "FD Scheme",
    rowIdColumn: "LINE_ID",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: false,
    pageSizes: [20, 30, 40],
    defaultPageSize: 20,
    containerHeight: {
      min: "50vh",
      max: "35vh",
    },
    allowFilter: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "id1",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "DISP_PERIOD",
      columnName: "Period",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 120,
      maxWidth: 400,
    },
    {
      accessor: "ADD_RATE",
      columnName: "Addition Int Rate",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 130,
      minWidth: 110,
      maxWidth: 200,
    },
    {
      accessor: "PRIN_AMT",
      columnName: "Deposit Amount in Factor of",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "MAT_AMT",
      columnName: "Maturity Amount",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "EnterLatestAppVersion",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "MAX_IN_CUST_ID",
      columnName: "Max Deposit Allow in a Customer ID",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "FACTOR",
      columnName: "Factor",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "SR_CD",
      columnName: "Sr. Cd.",
      sequence: 7,
      alignment: "left",
      isVisible: false,
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
