import { GridMetaDataType } from "@acuteinfo/common-base";
export const DocumentGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "21.4vh",
      max: "21.4vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    searchPlaceholder: "Documents",
    isCusrsorFocused: true,
    footerNote: "DocumentTabFooterNote",
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "SR_NO",
      sequence: 1,
      componentType: "default",
      alignment: "right",
      isAutoSequence: true,
      width: 80,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      columnName: "Document",
      accessor: "TEMPLATE_DESCRIPTION",
      sequence: 2,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      columnName: "Submitted",
      accessor: "SUBMIT",
      sequence: 3,
      componentType: "editableCheckbox",
      alignment: "center",
      isReadOnly: true,
      width: 120,
      minWidth: 100,
      maxWidth: 140,
    },
    {
      columnName: "ValidUpto",
      accessor: "VALID_UPTO",
      sequence: 4,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 120,
    },
    {
      columnName: "EnteredFrom",
      accessor: "DOC_TYPE",
      sequence: 5,
      componentType: "default",
      width: 120,
    },
    {
      columnName: "DocumentType",
      accessor: "TEMPLATE_DOC_TYPE",
      sequence: 6,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      columnName: "DocumentAmount",
      accessor: "DOC_AMOUNT",
      sequence: 7,
      componentType: "currency",
      alignment: "right",
      width: 160,
    },
  ],
};
