import { GridMetaDataType } from "@acuteinfo/common-base";

export const NpaCategoryMasterGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "NPA_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    allowRowSelection: false,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    defaultPageSize: 15,
    pageSizes: [15, 30, 50],
    containerHeight: {
      min: "55vh",
      max: "55vh",
    },
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      accessor: "Sr.No.",
      columnName: "SrNo",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 80,
      minWidth: 100,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "NPA_CD",
      columnName: "Code",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "NPA_PARENT_DISP",
      columnName: "Parent",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      showTooltip: true,
    },
    {
      accessor: "SECURE_PROV_PERC",
      columnName: "ProvisionSecureRate",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 155,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "UNSECURE_PROV_PERC",
      columnName: "ProvisionUnSecureRate",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "ASSET_CLS_DISP",
      columnName: "AssetClassificationCode",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "PENAL_ON_OD_OS_DISP",
      columnName: "CalculatePenalInterestOn",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "CONFIG_ID",
      columnName: "RecoveryID",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
