import { GridMetaDataType } from "@acuteinfo/common-base";

export const gridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Search Account Master",
    rowIdColumn: "INDEX",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowColumnHiding: false,
    disableGlobalFilter: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "CUSTOMER_ID",
      columnName: "Id",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "branch",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 110,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "type",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      accessor: "ACCT_CD",
      columnName: "Code",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "CONF_BAL",
      columnName: "balance",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "STATUS_DISP",
      columnName: "status",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 500,
    },

    {
      accessor: "LF_NO_DISP",
      columnName: "minorMajor",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "SURNAME",
      columnName: "surName",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ADD1",
      columnName: "Address1",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ADD2",
      columnName: "Address2",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ADD3",
      columnName: "Address3",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 100,
      maxWidth: 500,
    },
  ],
};
