import { GridMetaDataType } from "@acuteinfo/common-base";
export const ASBAGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ASBA",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      alignment: "right",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "DepCode",
      accessor: "DEPOSITORY_CODE",
      sequence: 2,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "AppFormDate",
      accessor: "TRAN_DT",
      sequence: 3,
      componentType: "date",
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      width: 130,
    },
    {
      columnName: "ApplicantRefNo",
      accessor: "APPLICANT_REF_NO",
      sequence: 4,
      componentType: "default",
      width: 130,
    },
    {
      columnName: "EnrollmentID",
      accessor: "ENROLLMENT_ID",
      sequence: 5,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "DPID",
      accessor: "DP_ID",
      sequence: 6,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "ClientID",
      accessor: "CLIENT_ID",
      sequence: 7,
      componentType: "default",
      showTooltip: true,
      width: 140,
    },
    {
      columnName: "FirstHolderName",
      accessor: "CUSTOMER_NM",
      sequence: 8,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      columnName: "FirstHolderPAN",
      accessor: "PAN_NO",
      sequence: 9,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "SecondHolderName",
      accessor: "ACCT_NM1",
      sequence: 10,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      columnName: "SecondHolderPAN",
      accessor: "PAN_NO1",
      sequence: 11,
      componentType: "default",
      width: 100,
    },
    {
      columnName: "ThirdHolderName",
      accessor: "ACCT_NM2",
      sequence: 12,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      columnName: "ThirdHolderPAN",
      accessor: "PAN_NO2",
      sequence: 13,
      componentType: "default",
      width: 100,
    },
  ],
};
