import { GridMetaDataType } from "@acuteinfo/common-base";

export const gridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "MODE_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowColumnHiding: true,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "MODE_CD",
      columnName: "Mode",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "MODE_NM",
      columnName: "Description",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 350,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "MIN_NO_OF_JOINT",
      columnName: "MinimumNoofJoints",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 160,
      maxWidth: 500,
    },
    {
      accessor: "MAX_NO_OF_JOINT",
      columnName: "MaximumNoofJoints",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 100,
      maxWidth: 500,
    },
  ],
};
