import { GridMetaDataType } from "@acuteinfo/common-base";

export const viewChangesGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "ViewChangesHederTitle",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: false,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "51vh",
      max: "51vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "ACTION",
      columnName: "Action",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 140,
    },
    {
      accessor: "COLUMN_NAME",
      columnName: "ColumnName",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "OLD_VALUE",
      columnName: "OldValue",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 90,
      minWidth: 70,
      maxWidth: 150,
    },

    {
      accessor: "NEW_VALUE",
      columnName: "NewValue",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 90,
      minWidth: 70,
      maxWidth: 150,
    },
    {
      accessor: "MODIFIED_BY",
      columnName: "ModifiedBy",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 70,
      maxWidth: 150,
    },

    {
      accessor: "MODIFIED_DATE",
      columnName: "ModifiedDate",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      accessor: "MACHINE_NM",
      columnName: "MachineName",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 145,
      minWidth: 70,
      maxWidth: 180,
    },
    {
      accessor: "SR_CD",
      columnName: "SrCode",
      sequence: 5,
      alignment: "left",
      componentType: "currecy",
      width: 80,
      minWidth: 60,
      maxWidth: 150,
    },
  ],
};
