import { GridMetaDataType } from "@acuteinfo/common-base";
export const SubsidyGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Subsidy",
    rowIdColumn: "index",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 120,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "23.7vh",
      max: "23.7vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      columnName: "SrNo",
      accessor: "sr",
      sequence: 1,
      componentType: "default",
      alignment: "right",
      width: 80,
      maxWidth: 100,
      minWidth: 50,
    },
    {
      columnName: "EffectiveDate",
      accessor: "EFFECTIVE_DT",
      sequence: 2,
      componentType: "date",
      alignment: "center",
      width: 100,
    },
    {
      columnName: "Amount",
      accessor: "AMOUNT",
      sequence: 3,
      componentType: "currency",
      width: 150,
      alignment: "right",
    },
    {
      columnName: "ExpiryDate",
      accessor: "EXPIRY_DT",
      sequence: 4,
      componentType: "date",
      alignment: "center",
      width: 100,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      sequence: 5,
      componentType: "default",
      showTooltip: true,
      width: 200,
    },
    {
      columnName: "EnteredDate",
      accessor: "ENTERED_DATE",
      sequence: 6,
      componentType: "date",
      alignment: "center",
      width: 100,
    },
    {
      columnName: "Active",
      accessor: "ACTIVE_FLAG",
      sequence: 7,
      componentType: "editableCheckbox",
      alignment: "center",
      isReadOnly: true,
      width: 120,
    },
    {
      columnName: "CreditToParty",
      accessor: "CR_TO_PARTY",
      sequence: 8,
      componentType: "editableCheckbox",
      alignment: "center",
      isReadOnly: true,
      width: 120,
    },
    {
      columnName: "DebitfromAC",
      accessor: "FULL_ACCTNO",
      alignment: "right",
      sequence: 9,
      componentType: "default",
      width: 200,
    },
    {
      columnName: "DebitACName",
      accessor: "TRF_ACCT_NM",
      sequence: 10,
      componentType: "default",
      showTooltip: true,
      width: 220,
    },
  ],
};
