import { GridMetaDataType } from "@acuteinfo/common-base";

export const LoanScheduleGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    defaultPageSize: 20,
    containerHeight: {
      min: "28vh",
      max: "36vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
    hideFooter: true,
    hideActionBar: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 40,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "DISBURSEMENT_DT",
      columnName: "DisbursementDate",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 140,
      minWidth: 140,
      maxWidth: 250,
    },
    {
      accessor: "DISBURSEMENT_AMT",
      columnName: "DisbursementAmount",
      sequence: 3,
      alignment: "right",
      componentType: "currency",
      width: 170,
      minWidth: 120,
      maxWidth: 250,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "INST_TYPE_DIS",
      columnName: "InstallmentType",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "INST_NO",
      columnName: "NoofInstallment",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "INS_START_DT",
      columnName: "NextInstallmentStartDate",
      sequence: 6,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 190,
      minWidth: 170,
      maxWidth: 250,
    },
    {
      accessor: "INST_RS",
      columnName: "DisburseInstallmentAmount",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 200,
      minWidth: 170,
      maxWidth: 250,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 400,
      minWidth: 220,
      maxWidth: 700,
      showTooltip: true,
    },
    {
      accessor: "SR_CD",
      columnName: "Srcd",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
      isVisible: false,
    },
  ],
};

export const LoanScheduleDetailsGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 350,
      minWidth: 300,
      maxWidth: 400,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    disableGroupBy: true,
    defaultPageSize: 20,
    containerHeight: {
      min: "45vh",
      max: "45vh",
    },
    isCusrsorFocused: true,
    allowRowSelection: false,
  },
  columns: [
    {
      accessor: "SR_CD",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 40,
      maxWidth: 100,
    },
    {
      accessor: "INS_START_DT",
      columnName: "InstallmentStartDate",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 170,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "BEGIN_BAL",
      columnName: "BeginningBalance",
      sequence: 3,
      alignment: "right",
      componentType: "currency",
      width: 190,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "INT_RATE",
      columnName: "InterestRate",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "INST_RS",
      columnName: "InstallmentAmount",
      sequence: 5,
      alignment: "right",
      componentType: "currency",
      width: 190,
      minWidth: 100,
      maxWidth: 200,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "PRIN_DEMAND_AMT",
      columnName: "PrincipalDemand",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 190,
      minWidth: 100,
      maxWidth: 200,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "INT_DEMAND_AMT",
      columnName: "InterestDemand",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 190,
      minWidth: 100,
      maxWidth: 200,
      isDisplayTotal: true,
      totalDecimalCount: 2,
    },
    {
      accessor: "END_BAL",
      columnName: "EndingBalance",
      sequence: 8,
      alignment: "right",
      componentType: "currency",
      width: 200,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      columnName: "Action",
      componentType: "buttonRowCell",
      accessor: "EDIT_BTN",
      sequence: 9,
      buttonLabel: "Edit",
      width: 100,
      minWidth: 80,
      maxWidth: 110,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.ALLOW_EDIT === "Y") {
          return false;
        }
        return true;
      },
    },
  ],
};
