import { GridMetaDataType } from "@acuteinfo/common-base";

export const releaseGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Transactions",
    rowIdColumn: "MCT_TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "30vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      accessor: "ACCT_TYPE",
      columnName: "Type",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "ACCT_CD",
      columnName: "Account",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "MCT_TRAN_CD",
      columnName: "ReferenceNumber",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "TYPE_CD",
      columnName: "Trx",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 60,
      maxWidth: 80,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 140,
      maxWidth: 160,
    },
    {
      accessor: "AMOUNT",
      columnName: "Amount",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      isDisplayTotal: true,
      width: 120,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "SDC",
      columnName: "SDC",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 100,
    },
    {
      accessor: "SCROLL1",
      columnName: "Scroll",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "ENTERED_COMP_CD",
      columnName: "TrBank",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 110,
      maxWidth: 130,
    },
    {
      accessor: "ENTERED_BRANCH_CD",
      columnName: "TrBranch",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 110,
      maxWidth: 130,
    },
  ],
};

export const releaseSubGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Release",
    rowIdColumn: "ROW_ID",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "30vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      accessor: "ACCT_CD",
      columnName: "AcctNum",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "MCT_TRAN_CD",
      columnName: "ReferenceNumber",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "TYPE_CD",
      columnName: "Trx",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 60,
      maxWidth: 80,
    },
    {
      accessor: "REMARKS",
      columnName: "Remarks",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 140,
      maxWidth: 160,
    },
    {
      accessor: "REC_AMOUNT",
      columnName: "Receipt",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      isDisplayTotal: true,
      width: 120,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "PAY_AMOUNT",
      columnName: "Payment",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      isDisplayTotal: true,
      width: 120,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "EnteredBy",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "SDC",
      columnName: "SDC",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 100,
    },
    {
      accessor: "SCROLL1",
      columnName: "Scroll",
      sequence: 10,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "ENTERED_COMP_CD",
      columnName: "Tr.Bank",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 110,
      maxWidth: 130,
    },
    {
      accessor: "ENTERED_BRANCH_CD",
      columnName: "TrBranch",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 110,
      maxWidth: 130,
    },
  ],
};
