export const RetrieveGridMetaData = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "INDEX",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    defaultPageSize: 20,
    containerHeight: {
      min: "60vh",
      max: "60vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "date",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      width: 150,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "TRAN_TYPE_DESC",
      columnName: "clearingType",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "DISPLAY_ACC_NO",
      columnName: "AccountNo",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AccountName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CHEQUE_NO",
      columnName: "ChequeNo",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 110,
    },
    {
      accessor: "AMOUNT",
      columnName: "amount",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 150,
      maxWidth: 250,
      isDisplayTotal: true,
    },

    {
      accessor: "BANK_NM",
      columnName: "BankName",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 210,
    },
    {
      accessor: "COMP_CD",
      columnName: "Bank",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 110,
    },
    {
      accessor: "ENTERED_BRANCH_CD",
      columnName: "enteredBranch",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 80,
      maxWidth: 200,
    },
  ],
};
