import { GridMetaDataType } from "@acuteinfo/common-base";

export const nscDetailGridData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "NSCDetail",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "57vh",
      max: "57vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "ID",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 76,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "CERTI_NO",
      columnName: "CertificateNumber",
      sequence: 2,
      alignment: "right",
      componentType: "default",
      width: 123,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "COLLATERAL_NAME",
      columnName: "CollateralName",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "COLLATERAL_AMT",
      columnName: "CollateralAmount",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 135,
      minWidth: 100,
      maxWidth: 150,
    },

    {
      accessor: "COLLATERAL_RATE",
      columnName: "CollateralRate",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 135,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "EnteredDate",
      sequence: 6,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 140,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "EXP_DATE",
      columnName: "ExpiryDate",
      sequence: 7,
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      componentType: "date",
      width: 116,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "ISSUE_COMPANY",
      columnName: "IssuedBy",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "ISSUE_DATE",
      columnName: "IssueDate",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 110,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "LIEN_ACCT_TYPE",
      columnName: "AccountType",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "LIEN_ACCT_CD",
      columnName: "AccountNumber",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 111,
      minWidth: 70,
      maxWidth: 130,
    },
    {
      accessor: "MATURED_AMT",
      columnName: "MaturedAmount",
      sequence: 12,
      alignment: "right",
      componentType: "currency",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "DISPLAY_PERIOD_CD",
      columnName: "PeriodType",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 105,
      minWidth: 70,
      maxWidth: 130,
    },
    {
      accessor: "PERIOD_NO",
      columnName: "PeriodNumber",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 94,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "REGISTRATION_NO",
      columnName: "RegistrationNumber",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 125,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "REMARK",
      columnName: "Remarks",
      sequence: 15,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
