import { GridMetaDataType } from "@acuteinfo/common-base";
export const VouchersDetailsGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: false,
    gridLabel: "VouchersDetails",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: false,
    containerHeight: {
      min: "20vh",
      max: "20vh",
    },
    allowRowSelection: false,
    hideFooter: true,
  },

  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "VoucherNumber",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 130,
      maxWidth: 150,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "AccountBranch",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 110,
      maxWidth: 130,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AccountType",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 110,
      maxWidth: 130,
    },
    {
      accessor: "ACCT_CD",
      columnName: "AccountNum",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 170,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "ACCT_NM",
      columnName: "AccountName",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 320,
      minWidth: 310,
      maxWidth: 350,
      showTooltip: true,
    },
    {
      accessor: "TYPE_CD",
      columnName: "TRX",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 60,
      minWidth: 50,
      maxWidth: 70,
    },
    {
      accessor: "REMARKS",
      columnName: "Narration",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 240,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "CR_AMOUNT",
      columnName: "Credit",
      sequence: 8,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 120,
      maxWidth: 220,
      isDisplayTotal: true,
      footerLabel: " ",
    },
    {
      accessor: "DR_AMOUNT",
      columnName: "Debit",
      sequence: 9,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 120,
      maxWidth: 220,
      isDisplayTotal: true,
      footerLabel: " ",
    },
  ],
};
