import { GridMetaDataType } from "@acuteinfo/common-base";
export const FDDetailForArrayFieldMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 250,
      maxWidth: 300,
      minWidth: 200,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "17vh",
      max: "17vh",
    },
    allowColumnHiding: false,
    allowRowSelection: false,
    hideFooter: true,
    isCusrsorFocused: true,
  },

  columns: [
    {
      accessor: "SrNo",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      isAutoSequence: true,
      width: 70,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "BranchCode",
      sequence: 2,
      alignment: "center",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "AccountType",
      sequence: 3,
      alignment: "center",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_CD",
      columnName: "AccountNum",
      sequence: 4,
      alignment: "right",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "FD_NO",
      columnName: "FDNo",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "TRAN_DT",
      columnName: "asonDate",
      sequence: 6,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "PERIOD_CD",
      columnName: "PeriodTenor",
      sequence: 7,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "PERIOD_NO",
      columnName: "Tenor",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "INT_RATE",
      columnName: "InterestRate",
      sequence: 9,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "TERM_CD",
      columnName: "InterestTerm",
      sequence: 10,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "MONTHLY_INT",
      columnName: "MonthInterest",
      sequence: 11,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "MATURITY_DT",
      columnName: "MaturityDate",
      sequence: 12,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 150,
    },
    {
      accessor: "CASH_AMT",
      columnName: "Cash",
      sequence: 13,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 90,
      maxWidth: 200,
    },
    {
      accessor: "TRSF_AMT",
      columnName: "TransferAmount",
      sequence: 14,
      alignment: "right",
      componentType: "currency",
      width: 130,
      minWidth: 90,
      maxWidth: 200,
    },
    {
      accessor: "CR_BRANCH_CD",
      columnName: "CreditBranchCode",
      sequence: 15,
      alignment: "center",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "CR_ACCT_TYPE",
      columnName: "CreditAcctType",
      sequence: 16,
      alignment: "center",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CR_ACCT_CD",
      columnName: "CreditAcctNo",
      sequence: 17,
      alignment: "right",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CR_ACCT_NM",
      columnName: "CreditAcctName",
      sequence: 18,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "MATURITY_AMT",
      columnName: "MaturityAmount",
      sequence: 19,
      alignment: "right",
      componentType: "currency",
      width: 130,
      minWidth: 90,
      maxWidth: 200,
    },
    {
      accessor: "MATURE_INST",
      columnName: "MatureInstruction",
      sequence: 20,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "FD_REMARK",
      columnName: "FDRemark",
      sequence: 21,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 350,
      showTooltip: true,
    },
    {
      accessor: "NOMINEE_NM",
      columnName: "NomineeName",
      sequence: 22,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 300,
      showTooltip: true,
    },
  ],
};
