import { GridMetaDataType } from "@acuteinfo/common-base";
export const PaidFDGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Paid FD Detail",
    rowIdColumn: "FD_NO",
    defaultColumnConfig: {
      width: 250,
      maxWidth: 300,
      minWidth: 200,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "45vh",
      max: "45vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_DT",
      columnName: "DepositDate",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
    },
    {
      accessor: "TOT_AMT",
      columnName: "PrincipalAmount",
      sequence: 3,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 130,
      maxWidth: 250,
      isDisplayTotal: true,
    },
    {
      accessor: "PAID_DT",
      columnName: "PaidDate",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "PAYMENT_MODE",
      columnName: "Payment",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "PAYMENT_AMT",
      columnName: "PaymentAmount",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 130,
      maxWidth: 250,
      isDisplayTotal: true,
    },
    {
      accessor: "MATURITY_DT",
      columnName: "MaturityDate",
      sequence: 7,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 130,
    },
    {
      accessor: "FD_NO",
      columnName: "FDNo",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 120,
    },
    {
      accessor: "PERIOD_DISP",
      columnName: "Period",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "INT_RATE",
      columnName: "Rate",
      sequence: 10,
      alignment: "right",
      componentType: "default",
      width: 90,
      minWidth: 80,
      maxWidth: 100,
    },
    {
      accessor: "TERM_DISP",
      columnName: "Term",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "INT_AMT",
      columnName: "FinIntAmt",
      sequence: 12,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 130,
      maxWidth: 250,
      isDisplayTotal: true,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "IssueDate",
      sequence: 13,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "FD_REMARK",
      columnName: "FDRemark",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "MATURITY_AMT",
      columnName: "MaturityAmount",
      sequence: 15,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 130,
      maxWidth: 250,
      isDisplayTotal: true,
    },
    {
      accessor: "TOT_TDS_RECO_INT_AMT",
      columnName: "TDSRecoverAmount",
      sequence: 16,
      alignment: "right",
      componentType: "currency",
      width: 170,
      minWidth: 150,
      maxWidth: 250,
      isDisplayTotal: true,
    },
    {
      accessor: "RENEW_REMARK",
      columnName: "RenewRemark",
      sequence: 17,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 300,
      showTooltip: true,
    },
    {
      accessor: "SR_CD",
      columnName: "SerialCode",
      sequence: 18,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 120,
      maxWidth: 140,
    },

    {
      accessor: "MATURE_INST",
      columnName: "MatureInstruction",
      sequence: 19,
      alignment: "left",
      componentType: "default",
      width: 230,
      minWidth: 200,
      maxWidth: 280,
      showTooltip: true,
    },

    {
      columnName: "",
      componentType: "buttonRowCell",
      accessor: "VIEW_ADVICE",
      sequence: 20,
      buttonLabel: "ViewAdvice",
      width: 100,
      minWidth: 80,
      maxWidth: 110,
    },
  ],
};
