import { GridMetaDataType } from "@acuteinfo/common-base";
import { GeneralAPI } from "registry/fns/functions";
export const RelatedAcGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "U_ID",
    defaultColumnConfig: {
      width: 250,
      maxWidth: 300,
      minWidth: 200,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "45vh",
      max: "45vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    footerNote: "DoubleClickOpenNewAccount",
    isCusrsorFocused: true,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "NEW_ACCT_TYPE",
      columnName: "NewType",
      sequence: 2,
      alignment: "left",
      componentType: "editableAutocomplete",
      width: 200,
      minWidth: 180,
      maxWidth: 250,
      options: (_, authState) => {
        return GeneralAPI.get_Account_Type({
          COMP_CD: authState?.companyID ?? "",
          BRANCH_CD: authState?.user?.branchCode ?? "",
          USER_NAME: authState?.user?.id ?? "",
          DOC_CD: "RELATEDACCT",
        });
      },
      _optionsKey: "get_Account_Type",
    },
    {
      accessor: "CUSTOMER_ID",
      columnName: "customerId",
      sequence: 3,
      alignment: "right",
      componentType: "default",
      width: 120,
      minWidth: 110,
      maxWidth: 150,
    },
    {
      accessor: "ACCT_NO",
      columnName: "ACNo",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 180,
      maxWidth: 250,
    },
    {
      accessor: "ACCT_NM",
      columnName: "Name",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 250,
      maxWidth: 400,
    },
    {
      accessor: "STATUS_NM",
      columnName: "Status",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 90,
      maxWidth: 110,
    },
    {
      accessor: "TRAN_BAL",
      columnName: "Balance",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 140,
      maxWidth: 200,
      isDisplayTotal: true,
    },
  ],
};
