import { GridMetaDataType } from "@acuteinfo/common-base";
export const SchemeSelectionGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "LINE_ID",
    defaultColumnConfig: {
      width: 250,
      maxWidth: 300,
      minWidth: 200,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    hideFooter: false,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "45vh",
      max: "45vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },

  columns: [
    {
      accessor: "SR_NO",
      columnName: "SrNo",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "PERIOD_DISP",
      columnName: "Period",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ADD_RATE",
      columnName: "AdditionalIntRate",
      sequence: 3,
      alignment: "right",
      componentType: "default",
      width: 120,
      minWidth: 110,
      maxWidth: 150,
    },
    {
      accessor: "PRIN_AMT",
      columnName: "DepositAmountFactorof",
      sequence: 4,
      alignment: "right",
      componentType: "currency",
      width: 210,
      minWidth: 180,
      maxWidth: 300,
      isDisplayTotal: true,
    },
    {
      accessor: "MAT_AMT",
      columnName: "MaturityAmount",
      sequence: 5,
      alignment: "right",
      componentType: "currency",
      width: 140,
      minWidth: 100,
      maxWidth: 300,
      isDisplayTotal: true,
    },
    {
      accessor: "MAX_IN_CUST_ID",
      columnName: "MaxDepositAllowCustomerID",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 230,
      minWidth: 180,
      maxWidth: 300,
      isDisplayTotal: true,
    },
    {
      accessor: "FACTOR",
      columnName: "Factor",
      sequence: 7,
      alignment: "right",
      componentType: "default",
      width: 130,
      minWidth: 100,
      maxWidth: 250,
    },
  ],
};
