import { GridMetaDataType } from "@acuteinfo/common-base";

import { GeneralAPI } from "registry/fns/functions";

export const standingInsructionGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 200,
      maxWidth: 450,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "65vh",
      max: "65vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "COMM_TYPE_DESC",
      columnName: "CommisionType",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 250,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "NO_OF_RECORD",
      columnName: "NoofRecords",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      columnName: "",
      componentType: "default",
      isVisible: false,
      accessor: "TRAN_CD",
      sequence: 6,
      width: 160,
      minWidth: 160,
      maxWidth: 200,
    },
    {
      columnName: "",
      componentType: "default",
      isVisible: false,
      accessor: "DEF_TRAN_CD",
      sequence: 6,
      width: 160,
      minWidth: 160,
      maxWidth: 200,
    },
  ],
};

export const standingInsructionViewGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "LINE_ID",
    defaultColumnConfig: {
      width: 200,
      maxWidth: 450,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "30vh",
      max: "30vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "CR_BRANCH_CD",
      columnName: "CreditBranchCode",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "CR_ACCT_TYPE",
      columnName: "CreditAcctType",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "CR_ACCT_CD",
      columnName: "Credit A/c No.",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      columnName: "",
      componentType: "buttonRowCell",
      buttonLabel: "CreditPhotoSign",
      accessor: "credit",
      width: 180,
      sequence: 4,
      alignment: "center",
      isVisible: true,
    },
    {
      accessor: "START_DT",
      columnName: "StartDate",
      sequence: 5,
      alignment: "left",
      componentType: "date",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "EXECUTE_DAY",
      columnName: "ExecuteOnDay",
      sequence: 6,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "FEQ_TYPE",
      columnName: "FrequncyType",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "FEQ_VALUE",
      columnName: "FrequencyValue",
      sequence: 8,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "DebitBranchCode",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "DR_ACCT_TYPE",
      columnName: "DebitAcctType",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "DR_ACCT_CD",
      columnName: "DebitAcctNo",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      columnName: "",
      componentType: "buttonRowCell",
      buttonLabel: "DebitPhotoSign",
      accessor: "debit",
      width: 180,
      sequence: 12,
      alignment: "center",
      isVisible: true,
    },
    {
      accessor: "SI_AMOUNT",
      columnName: "SIAmount",
      sequence: 13,
      componentType: "currency",
      alignment: "right",
      width: 180,
      minWidth: 150,
      maxWidth: 200,
      isDisplayTotal: true,
    },
    {
      accessor: "SI_CHARGE",
      columnName: "SICharge",
      sequence: 14,
      alignment: "right",
      componentType: "currency",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "REMARKS",
      columnName: "Remark",
      sequence: 15,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 350,
    },
    {
      accessor: "VALID_UPTO",
      columnName: "ValidUpTo",
      sequence: 16,
      alignment: "left",
      componentType: "date",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "SI_COUNT",
      columnName: "",
      sequence: 17,
      alignment: "left",
      isVisible: false,
      componentType: "default",
      isReadOnly: true,
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "DOC_STATUS",
      columnName: "Status",
      sequence: 18,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
      isVisible: true,
      isReadOnly: true,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.SI_COUNT > 0) {
          return false;
        } else {
          return true;
        }
      },
    },
    {
      accessor: "SI_NUMBER",
      columnName: "SINumber",
      sequence: 19,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "CR_ACCT_NM",
      columnName: "CreditAcctName",
      sequence: 20,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 50,
      maxWidth: 350,
    },
    {
      accessor: "DR_ACCT_NM",
      columnName: "DebitAcctName",
      sequence: 21,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 50,
      maxWidth: 350,
    },

    {
      columnName: "",
      componentType: "buttonRowCell",
      buttonLabel: "...",
      accessor: "edit",
      width: 80,
      sequence: 22,
      alignment: "center",
      isVisible: true,
    },
    {
      columnName: "",
      componentType: "buttonRowCell",
      buttonLabel: "Delete",
      accessor: "delete",
      width: 80,
      sequence: 23,
      alignment: "center",
      isVisible: true,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.SI_COUNT <= 0) {
          return false;
        } else {
          return true;
        }
      },
    },
  ],
};

export const siasExecutedGridMetadata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "INDEX",
    defaultColumnConfig: {
      width: 200,
      maxWidth: 450,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: true,
    hideFooter: false,
    disableGroupBy: true,
    enablePagination: false,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "40vh",
      max: "40vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SR_NO",
      isAutoSequence: true,
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "EXECUTE_DT",
      columnName: "Executedate",
      sequence: 1,
      alignment: "left",
      componentType: "date",
      width: 150,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "CR_BRANCH_CD",
      columnName: "CreditBranchCode",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "CR_ACCT_TYPE",
      columnName: "CreditAcctType",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "CR_ACCT_CD",
      columnName: "CreditAcctNo",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "SI_AMOUNT",
      columnName: "Amount",
      sequence: 3,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 50,
      maxWidth: 170,
    },
    {
      accessor: "SI_EXECUTE_FLG",
      columnName: "Processed",
      sequence: 4,
      alignment: "left",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
      componentType: "editableAutocomplete",
      options: () => [{ label: "Consider As Executed", value: "C" }],
      _optionsKey: "getProcessedStatus",
    },
    {
      accessor: "REASON",
      columnName: "Reason",
      sequence: 5,
      alignment: "left",
      componentType: "editableTextField",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
    },
  ],
};

export const searchButttonGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "SearchSI",
    rowIdColumn: "INDEX",
    defaultColumnConfig: {
      width: 200,
      maxWidth: 450,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    hideFooter: true,
    disableGroupBy: true,
    enablePagination: false,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "67vh",
      max: "67vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SrNo",
      columnName: "SrNo",
      sequence: 1,
      alignment: "center",
      componentType: "default",
      width: 75,
      minWidth: 70,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "DEBIT_ACCOUNT",
      columnName: "Debit From A/C",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "DR_ACCT_NM",
      columnName: "Debit A/C Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 50,
      maxWidth: 350,
    },
    {
      accessor: "START_DT",
      columnName: "StartDate",
      sequence: 4,
      alignment: "left",
      componentType: "date",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "EXECUTE_DAY",
      columnName: "ExecuteOnDay",
      sequence: 5,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "FEQ_TYPE",
      columnName: "FrequncyType",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "FEQ_VALUE",
      columnName: "FrequencyValue",
      sequence: 7,
      alignment: "right",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "CREDIT_ACCOUNT",
      columnName: "CreditToAccount",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CR_ACCT_NM",
      columnName: "CreditAcctName",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 50,
      maxWidth: 350,
    },
    {
      accessor: "SI_AMOUNT",
      columnName: "SIAmount",
      sequence: 10,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 50,
      maxWidth: 170,
    },
    {
      accessor: "SI_CHARGE",
      columnName: "SICharge",
      sequence: 11,
      alignment: "right",
      componentType: "currency",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "REMARKS",
      columnName: "Remark",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 350,
    },
    {
      accessor: "VALID_UPTO",
      columnName: "ValidUpto",
      sequence: 13,
      alignment: "left",
      componentType: "date",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "DOC_STATUS",
      columnName: "Status",
      sequence: 14,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
      isReadOnly: true,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.SI_COUNT > 0) {
          return false;
        } else {
          return true;
        }
      },
    },

    {
      columnName: "",
      componentType: "buttonRowCell",
      buttonLabel: "Delete",
      accessor: "delete",
      width: 80,
      sequence: 15,
      alignment: "center",
      isVisible: true,
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.SI_COUNT <= 0) {
          return false;
        } else {
          return true;
        }
      },
    },
  ],
};

export const siExecuteDetailViewGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Standing Instruction Execute Detail View",
    rowIdColumn: "SUB_LINE_ID",
    defaultColumnConfig: {
      width: 200,
      maxWidth: 450,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    footerNote: "DeletetheTransaction",
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "70vh",
      max: "70vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "SrNo",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      isAutoSequence: true,
      width: 80,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "EXECUTE_DT",
      columnName: "Executedate",
      sequence: 2,
      alignment: "center",
      componentType: "date",
      width: 120,
      minWidth: 100,
      maxWidth: 150,
      isDisplayTotal: true,
      footerLabel: "Processed",
      setFooterValue(total, rows) {
        const proccessedCount = rows?.filter(
          ({ original }) =>
            original.SI_EXECUTE_FLG === "Y" || original.SI_EXECUTE_FLG === "C"
        ).length;
        return [proccessedCount ?? 0];
      },
    },
    {
      accessor: "PROCESS_DT",
      columnName: "ProcessDate",
      sequence: 3,
      alignment: "center",
      componentType: "date",
      width: 120,
      minWidth: 100,
      maxWidth: 150,
      isDisplayTotal: true,
      footerLabel: "Pending",
      setFooterValue(total, rows) {
        const pendingCount = rows?.filter(
          ({ original }) => original?.SI_EXECUTE_FLG === "N"
        ).length;
        return [pendingCount ?? 0];
      },
    },
    {
      accessor: "SI_EXECUTE_FLG_DIS",
      columnName: "SIExecuteProcess",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "REASON",
      columnName: "Reason",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "DebitBranchCode",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 195,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "DR_ACCT_TYPE",
      columnName: "DebitAcctType",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "DR_ACCT_CD",
      columnName: "DebitAcctNo",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CR_BRANCH_CD",
      columnName: "CreditBranchCode",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 195,
      minWidth: 150,
      maxWidth: 250,
    },
    {
      accessor: "CR_ACCT_TYPE",
      columnName: "CreditAcctType",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CR_ACCT_CD",
      columnName: "CreditAcctNo",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "SI_AMOUNT",
      columnName: "SIAmount",
      sequence: 9,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 50,
      maxWidth: 170,
      isDisplayTotal: true,
    },
    {
      accessor: "SI_CHARGE",
      columnName: "SICharge",
      sequence: 10,
      alignment: "right",
      componentType: "currency",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
      isDisplayTotal: true,
    },
    {
      accessor: "REMARKS",
      columnName: "Remark",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 350,
    },
    {
      columnName: "",
      componentType: "buttonRowCell",
      buttonLabel: "AuditTrail",
      accessor: "_hidden2",
      width: 140,
      sequence: 14,
      alignment: "center",
      shouldExclude: (initialValue, original, prevRows, nextRows) => {
        if (original?.AUDIT_CNT > 0) {
          return false;
        } else {
          return true;
        }
      },
    },
  ],
};

export const AuditgridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Standing Instruction Execute Detail View",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 200,
      maxWidth: 450,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableGlobalFilter: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "70vh",
      max: "70vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
  },
  columns: [
    {
      accessor: "Sr No.",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      isAutoSequence: true,
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "ACTIVITY_TIME",
      columnName: "ActivityTime",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "COLUMN_LABEL",
      columnName: "ColumnName",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "OLD_VALUE",
      columnName: "OldValue",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "NEW_VALUE",
      columnName: "NewValue",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "USER_NM",
      columnName: "Maker",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "ACTIVITY_DATE",
      columnName: "Act. Date",
      sequence: 5,
      alignment: "left",
      componentType: "date",
      width: 120,
      minWidth: 80,
      maxWidth: 150,
    },
  ],
};

export const populateGridData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "SUB_LINE_ID",
    defaultColumnConfig: { width: 150, maxWidth: 250, minWidth: 100 },
    allowColumnReordering: true,
    hideHeader: true,
    disableGroupBy: true,
    containerHeight: { min: "25vh", max: "25vh" },
    allowRowSelection: false,
    hiddenFlag: "_hidden",
    disableLoader: true,
    paginationText: "Records found",
  },
  columns: [
    {
      accessor: "Sr No.",
      columnName: "SrNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      isAutoSequence: true,
      width: 50,
      minWidth: 40,
      maxWidth: 100,
    },
    {
      accessor: "EXECUTE_DT",
      columnName: "ExecuteDate",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "PROCESS_DT",
      columnName: "ProcessDate",
      sequence: 3,
      alignment: "left",
      componentType: "date",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "SI_EXECUTE_FLG_DIS",
      columnName: "SIExecuteProcess",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "REASON",
      columnName: "Reason",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "BRANCH_CD",
      columnName: "DebitBranchCode",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "DR_ACCT_TYPE",
      columnName: "DebitAcctType",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "DR_ACCT_CD",
      columnName: "DebitAcctNo",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "CR_BRANCH_CD",
      columnName: "CreditBranchCode",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "CR_ACCT_TYPE",
      columnName: "CreditAcctType",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 350,
    },
    {
      accessor: "CR_ACCT_CD",
      columnName: "CreditAcctNo",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 50,
      maxWidth: 350,
    },
    {
      accessor: "SI_AMOUNT",
      columnName: "SIAmount",
      sequence: 12,
      alignment: "right",
      componentType: "currency",
      width: 150,
      minWidth: 50,
      maxWidth: 170,
    },
    {
      accessor: "SI_CHARGE",
      columnName: "SICharge",
      sequence: 13,
      alignment: "right",
      componentType: "currency",
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
    {
      accessor: "REMARKS",
      columnName: "Remark",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 350,
    },
  ],
};
