import { GridMetaDataType } from "@acuteinfo/common-base";

export const retrieveGridMetaData = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "INDEX",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    disableGlobalFilter: false,
    enablePagination: true,
    pageSizes: [15, 30, 50],
    defaultPageSize: 50,
    containerHeight: {
      min: "70vh",
      max: "70vh",
    },
    allowFilter: false,
    footerNote: "DoEntryConfirmNotev",
    allowColumnHiding: false,
    allowRowSelection: false,
    allowGlobal: false,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      accessor: "BRANCH_CD",
      columnName: "branch",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "ACCT_TYPE",
      columnName: "Type",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "ACCT_CD",
      columnName: "ACNo",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "ACCT_NM",
      columnName: "accountName",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 200,
      maxWidth: 400,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "maker",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "lastModifiedDate",
      sequence: 1,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 170,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "MACHINE_NM",
      columnName: "machinename",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "NEW_SIGN",
      columnName: "",
      componentType: "icondefault",
      sequence: 14,
      alignment: "center",
      width: 50,
      minWidth: 70,
      maxWidth: 150,
      isImageURL: false,
    },
    {
      accessor: "NEW_SIGN_VIEW",
      columnName: "newSign",
      componentType: "buttonRowCell",
      buttonLabel: "View",
      sequence: 14,
      alignment: "right",
      width: 120,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "NEW_PHOTO",
      columnName: "",
      componentType: "icondefault",
      sequence: 14,
      alignment: "center",
      width: 50,
      minWidth: 70,
      maxWidth: 150,
      isImageURL: false,
    },
    {
      accessor: "NEW_PHOTO_VIEW",
      columnName: "newPhoto",
      componentType: "buttonRowCell",
      buttonLabel: "View",
      sequence: 14,
      alignment: "right",
      width: 120,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "OLD_SIGN",
      columnName: "",
      componentType: "icondefault",
      sequence: 14,
      alignment: "center",
      width: 50,
      minWidth: 70,
      maxWidth: 150,
      isImageURL: false,
    },
    {
      accessor: "OLD_SIGN_VIEW",
      columnName: "oldSign",
      componentType: "buttonRowCell",
      buttonLabel: "View",
      sequence: 14,
      alignment: "right",
      width: 120,
      minWidth: 70,
      maxWidth: 100,
    },
    {
      accessor: "OLD_PHOTO",
      columnName: "",
      componentType: "icondefault",
      sequence: 14,
      alignment: "center",
      width: 50,
      minWidth: 70,
      maxWidth: 150,
      isImageURL: false,
    },
    {
      accessor: "OLD_PHOTO_VIEW",
      columnName: "oldPhoto",
      componentType: "buttonRowCell",
      buttonLabel: "View",
      sequence: 14,
      alignment: "right",
      width: 120,
      minWidth: 70,
      maxWidth: 100,
    },
  ],
};
