export const impsCfmMetaData = {
  masterForm: {
    form: {
      name: "imps-Confirm-MetaData",
      label: " ",
      resetFieldOnUnmount: false,
      validationRun: "onBlur",
      render: {
        ordering: "auto",
        renderType: "simple",
        gridConfig: {
          item: {
            xs: 12,
            sm: 4,
            md: 4,
          },
          container: {
            direction: "row",
            spacing: 1.5,
          },
        },
      },
    },
    fields: [
      {
        render: {
          componentType: "typography",
        },
        name: "TOTAL",
        label: "",
        fullWidth: true,
        shouldExclude: (field) => {
          if (field?.value) {
            return false;
          }
          return true;
        },
        TypographyProps: { variant: "subtitle2" },
        GridProps: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
          xl: 12,
          pt: "6px !important",
        },
      },
      {
        render: {
          componentType: "numberFormat",
        },
        name: "CUSTOMER_ID",
        fullWidth: true,
        label: "CustomerId",
        GridProps: {
          xs: 12,
          md: 2.5,
          sm: 2.5,
          lg: 2.5,
          xl: 2.5,
        },
      },

      {
        render: {
          componentType: "textField",
        },
        name: "ORGINAL_NM",
        label: "AcctOrignalName",
        fullWidth: true,
        GridProps: {
          xs: 12,
          md: 4.5,
          sm: 4.5,
          lg: 4.5,
          xl: 4.5,
        },
      },
      {
        render: {
          componentType: "phoneNumberOptional",
        },
        name: "MOB_NO",
        label: "MobileNo",
        fullWidth: true,
        GridProps: {
          xs: 12,
          md: 2.5,
          sm: 2.5,
          lg: 2.5,
          xl: 2.5,
        },
      },

      {
        render: {
          componentType: "aadharCard",
        },
        name: "UNIQUE_ID",
        label: "UIDAadhaar",
        fullWidth: true,
        GridProps: { xs: 12, md: 2.5, sm: 2.5, lg: 2.5, xl: 2.5 },
      },

      {
        render: {
          componentType: "panCardOptional",
        },
        name: "PAN_NO",
        label: "PanNo",
        fullWidth: true,
        txtTransform: "uppercase",
        required: true,
        GridProps: { xs: 12, md: 2.5, sm: 2.5, lg: 2.5, xl: 2.5 },
      },
      {
        render: {
          componentType: "datetimePicker",
        },
        name: "REG_DATE",
        label: "ActivationDate",
        format: "dd/MM/yyyy HH:mm:ss",
        fullWidth: true,
        isReadOnly: true,
        GridProps: { xs: 12, md: 2.5, sm: 2.5, lg: 2.5, xl: 2.5 },
      },
      {
        render: {
          componentType: "checkbox",
        },
        name: "ACTIVE",
        label: "Active",
        fullWidth: true,
        isReadOnly: true,
        GridProps: {
          xs: 12,
          md: 2,
          sm: 2,
          lg: 2,
          xl: 2,
        },
      },
      {
        render: {
          componentType: "datePicker",
        },
        name: "DEACTIVE_DT",
        fullWidth: true,
        label: "DeActiveDateIMPS",
        GridProps: {
          xs: 12,
          md: 2.5,
          sm: 2.5,
          lg: 2.5,
          xl: 2.5,
        },
      },
    ],
  },

  detailsGrid: {
    gridConfig: {
      dense: true,
      gridLabel: "",
      rowIdColumn: "SR_CD",
      searchPlaceholder: "Accounts",
      defaultColumnConfig: {
        width: 150,
        maxWidth: 250,
        minWidth: 100,
      },
      allowColumnReordering: true,
      disableSorting: false,
      hideHeader: true,
      hideFooter: true,
      disableGroupBy: true,
      hiddenFlag: "_hidden",
      enablePagination: false,
      pageSizes: [10, 20, 30],
      defaultPageSize: 10,
      containerHeight: {
        min: "54vh",
        max: "54vh",
      },
      allowFilter: false,
      allowColumnHiding: false,
      allowRowSelection: false,
    },
    // filters: [],
    columns: [
      {
        accessor: "SRNO",
        columnName: "SrNo",
        sequence: 1,
        componentType: "default",
        width: 75,
        minWidth: 50,
        maxWidth: 100,
        isAutoSequence: true,
      },
      {
        accessor: "REG_DT",
        columnName: "RegDate",
        sequence: 2,
        componentType: "date",
        dateFormat: "dd/MM/yyyy",
        width: 135,
        maxWidth: 150,
        minWidth: 80,
        alignment: "center",
      },
      {
        accessor: "BRANCH_CD",
        columnName: "BranchCode",
        componentType: "default",
        sequence: 3,
        width: 120,
        minWidth: 100,
        maxWidth: 160,
      },

      {
        accessor: "ACCT_TYPE",
        columnName: "AccountType",
        componentType: "default",
        sequence: 3,
        width: 120,
        minWidth: 100,
        maxWidth: 160,
      },
      {
        accessor: "ACCT_CD",
        columnName: "AccountNumber",
        componentType: "default",
        sequence: 5,
        width: 150,
        minWidth: 80,
        maxWidth: 180,
      },
      {
        accessor: "ACCT_NM",
        columnName: "AccountName",
        componentType: "default",
        sequence: 6,
        width: 200,
        minWidth: 100,
        maxWidth: 220,
      },

      {
        accessor: "IFT",
        columnName: "",
        componentType: "editableCheckbox",
        isReadOnly: true,
        sequence: 7,
        alignment: "center",
        width: 70,
        minWidth: 30,
        maxWidth: 90,
      },
      {
        accessor: "PERDAY_IFT_LIMIT",
        columnName: "IFTDailyLimit",
        sequence: 8,
        componentType: "currency",
        width: 170,
        minWidth: 100,
        maxWidth: 200,
        alignment: "right",
      },
      {
        accessor: "RTGS",
        columnName: "",
        componentType: "editableCheckbox",
        isReadOnly: true,
        sequence: 9,
        alignment: "center",
        width: 70,
        minWidth: 30,
        maxWidth: 90,
      },
      {
        accessor: "PERDAY_RTGS_LIMIT",
        columnName: "RTGSDayLimit",
        sequence: 10,
        componentType: "currency",
        width: 170,
        minWidth: 100,
        maxWidth: 200,
        alignment: "right",
      },
      {
        accessor: "NEFT",
        columnName: "",
        componentType: "editableCheckbox",
        isReadOnly: true,
        sequence: 11,
        alignment: "center",
        width: 70,
        minWidth: 30,
        maxWidth: 90,
      },
      {
        accessor: "PERDAY_NEFT_LIMIT",
        columnName: "NEFTDayLimit",
        sequence: 12,
        componentType: "currency",
        width: 170,
        minWidth: 100,
        maxWidth: 200,
        alignment: "right",
      },
      {
        accessor: "IMPS",
        columnName: "",
        componentType: "editableCheckbox",
        isReadOnly: true,
        sequence: 13,
        alignment: "center",
        width: 70,
        minWidth: 30,
        maxWidth: 90,
      },
      {
        accessor: "PERDAY_P2P_LIMIT",
        columnName: "IMPSP2PDayLimit",
        sequence: 14,
        componentType: "currency",
        width: 170,
        minWidth: 100,
        maxWidth: 200,
        alignment: "right",
      },
      {
        accessor: "PERDAY_P2A_LIMIT",
        columnName: "IMPSP2ADayLimit",
        sequence: 15,
        componentType: "currency",
        width: 170,
        minWidth: 100,
        maxWidth: 200,
        alignment: "right",
      },
      {
        accessor: "OWN_ACT",
        columnName: "",
        componentType: "editableCheckbox",
        isReadOnly: true,
        sequence: 16,
        alignment: "center",
        width: 70,
        minWidth: 30,
        maxWidth: 90,
      },
      {
        accessor: "PERDAY_OWN_LIMIT",
        columnName: "OWNDayLimit",
        sequence: 17,
        componentType: "currency",
        width: 170,
        minWidth: 100,
        maxWidth: 200,
        alignment: "right",
      },
      {
        accessor: "BBPS",
        columnName: "",
        componentType: "editableCheckbox",
        isReadOnly: true,
        sequence: 18,
        alignment: "center",
        width: 70,
        minWidth: 30,
        maxWidth: 90,
      },
      {
        accessor: "PERDAY_BBPS_LIMIT",
        columnName: "BBPSDayLimit",
        sequence: 19,
        componentType: "currency",
        width: 170,
        minWidth: 100,
        maxWidth: 200,
        alignment: "right",
      },
      {
        accessor: "PG_TRN",
        columnName: "",
        componentType: "editableCheckbox",
        isReadOnly: true,
        sequence: 20,
        alignment: "center",
        width: 70,
        minWidth: 30,
        maxWidth: 90,
      },
      {
        accessor: "PERDAY_PG_AMT",
        columnName: "PGatewayDayLimit",
        sequence: 21,
        componentType: "currency",
        width: 170,
        minWidth: 100,
        maxWidth: 200,
        alignment: "right",
      },
    ],
  },
};
